### ISSUE TITLE
Bug in test for ternary operator

### ISSUE THREAD

**Issue by wifelette** [learn-co-curriculum/operators#24]
This is the final test in the spec:

```
it 'uses the ternary operator' do
      methods = file_contents.split("not_safe?")
      match = methods.last
      expect(match).to include("||")
    end
```

But shouldn't it be... 

```
it 'uses the ternary operator' do
      methods = file_contents.split("not_safe?")
      match = methods.last
      expect(match).to include("?")
    end
```

I got all my tests to pass but the last one, which was _supposed_ to be checking for `?` but instead appears to be checking for `||`. 

Seems like a simple bug, unless there's something I don't yet understand about how `||` == `?`? I don't think so... :stuck_out_tongue: 

Fixing the test got it to work. I assume that was preferable to using `||` but not `?`, since the point of the exercise was to learn to use `?`.

**Comment by SophieDeBenedetto** [comment]
Hi @wifelette, both the `||` and the `?` are used in creating an expression using the ternary operator. We just strengthened that test to check for both. Thanks!

**Comment by wifelette** [comment]
This works without using `||`:

```
def not_safe?(speed)
  speed > 40 && speed < 60 ? false : true
end
```

What am I missing? This lesson isn't about `||`, so I'm unsure why it would be important to go a route that uses that particular thing.

**Comment by SophieDeBenedetto** [comment]
looks, like you're correct. thanks and fixing now.

**Comment by wifelette** [comment]
:+1:
