### ISSUE TITLE
Posted solution is different from instructions solution, please review.

### ISSUE THREAD

**Issue by oliverbebber** [learn-co-curriculum/operators#35]
<img width="1440" alt="Screen Shot 2020-08-19 at 12 53 30 AM" src="https://user-images.githubusercontent.com/67529552/90594133-ad3de180-e1b7-11ea-8e41-66c0100cf825.png">
<img width="1440" alt="Screen Shot 2020-08-19 at 12 55 52 AM" src="https://user-images.githubusercontent.com/67529552/90594140-b464ef80-e1b7-11ea-9660-d08593d999c6.png">

**Comment by lizbur10** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
